/**
 * Mock stock pitch pipeline + archive data for org-team-hub demos.
 */

export const PITCH_STAGES = [
  'idea',
  'research_approved',
  'research_in_progress',
  'pm_review',
  'committee_scheduled',
  'committee_vote',
  'decision',
];

export const PIPELINE_COLUMNS = [
  { id: 'ideas', label: 'Ideas', stages: ['idea'] },
  { id: 'research', label: 'Research', stages: ['research_approved', 'research_in_progress'] },
  { id: 'pm_review', label: 'PM Review', stages: ['pm_review'] },
  { id: 'committee', label: 'Committee', stages: ['committee_scheduled'] },
  { id: 'voting', label: 'Voting', stages: ['committee_vote'] },
  { id: 'decided', label: 'Decided', stages: ['decision'] },
];

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();

export const MOCK_PITCHES = [
  {
    id: 'pitch-amd-1',
    team_id: 't7',
    ticker: 'AMD',
    company_name: 'Advanced Micro Devices',
    pitch_type: 'long',
    analyst_member_id: 'm10',
    approving_pm_member_id: null,
    stage: 'idea',
    status: 'active',
    thesis_short: 'AI accelerator share gain vs NVDA incumbent advantage',
    thesis_full:
      'AMD MI300X is gaining traction in hyperscaler pilots. We see meaningful share shift in training workloads over 18 months.',
    why_now: 'Hyperscaler capex cycle accelerating; AMD guidance revision likely at next earnings.',
    catalysts: ['MI300X volume ramp', 'Hyperscaler pilot conversions'],
    risks: ['NVDA CUDA moat', 'China export restrictions'],
    target_price: 195,
    current_price_at_submission: 162.4,
    expected_return_pct: 20,
    time_horizon: '6m',
    committee_meeting_at: null,
    decision: null,
    decision_at: null,
    decision_rationale: null,
    vote_yes_count: 0,
    vote_no_count: 0,
    vote_abstain_count: 0,
    research_due_at: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    archived_at: null,
  },
  {
    id: 'pitch-lulu-1',
    team_id: 't2',
    ticker: 'LULU',
    company_name: 'Lululemon',
    pitch_type: 'long',
    analyst_member_id: 'm17',
    approving_pm_member_id: null,
    stage: 'idea',
    status: 'active',
    thesis_short: 'International expansion driving margin re-rating',
    thesis_full: 'LULU international comps accelerating while North America stabilizes.',
    why_now: 'Post-correction valuation attractive vs historical premium.',
    catalysts: ['China reopening', 'New store openings'],
    risks: ['Athleisure competition', 'Consumer slowdown'],
    target_price: 520,
    current_price_at_submission: 385,
    expected_return_pct: 35,
    time_horizon: '12m',
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
  },
  {
    id: 'pitch-shop-1',
    team_id: 't7',
    ticker: 'SHOP',
    company_name: 'Shopify',
    pitch_type: 'long',
    analyst_member_id: 'm12',
    approving_pm_member_id: null,
    stage: 'idea',
    status: 'active',
    thesis_short: 'Merchant solutions attach rate inflecting post logistics divestiture',
    thesis_full: 'Focus on software margins should drive EBITDA expansion.',
    why_now: 'Logistics sale complete; Street underestimating take-rate stability.',
    catalysts: ['GMV acceleration', 'Payments attach'],
    risks: ['Competition from Adobe', 'SMB churn'],
    target_price: 95,
    current_price_at_submission: 72,
    expected_return_pct: 32,
    time_horizon: '12m',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: 'pitch-nvda-1',
    team_id: 't7',
    ticker: 'NVDA',
    company_name: 'NVIDIA',
    pitch_type: 'long',
    analyst_member_id: 'm10',
    approving_pm_member_id: 'm3',
    stage: 'research_in_progress',
    status: 'active',
    thesis_short: 'AI infrastructure demand is structural, not cyclical',
    thesis_full:
      'Data center GPU TAM expanding faster than supply. NVDA maintains software + hardware stack advantage.',
    why_now: 'Blackwell ramp and sovereign AI budgets provide multi-year visibility.',
    catalysts: ['Blackwell shipments', 'Sovereign AI deals'],
    risks: ['Custom ASIC competition', 'Export controls'],
    target_price: 950,
    current_price_at_submission: 875.3,
    expected_return_pct: 9,
    time_horizon: '6m',
    research_due_at: '2026-04-12T23:59:00Z',
    created_at: daysAgo(14),
    updated_at: daysAgo(3),
  },
  {
    id: 'pitch-bac-1',
    team_id: 't4',
    ticker: 'BAC',
    company_name: 'Bank of America',
    pitch_type: 'long',
    analyst_member_id: 'm16',
    approving_pm_member_id: 'm6',
    stage: 'research_in_progress',
    status: 'active',
    thesis_short: 'NIM expansion + buybacks support EPS growth above peers',
    thesis_full: 'Rate path and deposit mix favor BAC vs money-center peers.',
    why_now: 'Fed pause priced; credit quality resilient.',
    catalysts: ['NIM peak', 'Buyback acceleration'],
    risks: ['CRE office exposure', 'Regulatory capital'],
    target_price: 48,
    current_price_at_submission: 38.2,
    expected_return_pct: 26,
    time_horizon: '12m',
    research_due_at: '2026-04-18T23:59:00Z',
    created_at: daysAgo(10),
    updated_at: daysAgo(4),
  },
  {
    id: 'pitch-xom-1',
    team_id: 't3',
    ticker: 'XOM',
    company_name: 'Exxon Mobil',
    pitch_type: 'long',
    analyst_member_id: 'm15',
    approving_pm_member_id: 'm5',
    stage: 'research_approved',
    status: 'active',
    thesis_short: 'Capital discipline + Guyana volumes underpin FCF yield',
    thesis_full: 'Integrated model resilient; shareholder returns prioritized.',
    why_now: 'Oil strip supportive; valuation vs history attractive.',
    catalysts: ['Guyana FPSO ramp', 'Buybacks'],
    risks: ['Oil price collapse', 'Energy transition policy'],
    target_price: 135,
    current_price_at_submission: 118,
    expected_return_pct: 14,
    time_horizon: '12m',
    research_due_at: '2026-04-20T23:59:00Z',
    created_at: daysAgo(8),
    updated_at: daysAgo(6),
  },
  {
    id: 'pitch-jnj-hc-1',
    team_id: 't1',
    ticker: 'ISRG',
    company_name: 'Intuitive Surgical',
    pitch_type: 'long',
    analyst_member_id: 'm14',
    approving_pm_member_id: 'm4',
    stage: 'research_in_progress',
    status: 'active',
    thesis_short: 'da Vinci 5 adoption curve under-modeled by Street',
    thesis_full: 'Procedure growth re-accelerating post pandemic backlog clearance.',
    why_now: 'New system launch driving hospital upgrade cycle.',
    catalysts: ['da Vinci 5 placements', 'Procedure volume'],
    risks: ['Hospital capex cuts', 'Competition from J&J'],
    target_price: 520,
    current_price_at_submission: 445,
    expected_return_pct: 17,
    time_horizon: '12m',
    research_due_at: '2026-04-14T23:59:00Z',
    created_at: daysAgo(12),
    updated_at: daysAgo(5),
  },
  {
    id: 'pitch-cat-1',
    team_id: 't5',
    ticker: 'CAT',
    company_name: 'Caterpillar',
    pitch_type: 'long',
    analyst_member_id: 'm18',
    approving_pm_member_id: 'm8',
    stage: 'research_in_progress',
    status: 'active',
    thesis_short: 'Infrastructure bill tailwind on dealer inventory normalization',
    thesis_full: 'Dealer inventories lean; pricing power intact.',
    why_now: 'IIJA spend hitting heavy equipment orders.',
    catalysts: ['Dealer restocking', 'Mining capex'],
    risks: ['China construction slowdown', 'Rate sensitivity'],
    target_price: 380,
    current_price_at_submission: 325,
    expected_return_pct: 17,
    time_horizon: '6m',
    research_due_at: '2026-04-16T23:59:00Z',
    created_at: daysAgo(9),
    updated_at: daysAgo(7),
  },
  {
    id: 'pitch-fcx-1',
    team_id: 't6',
    ticker: 'FCX',
    company_name: 'Freeport-McMoRan',
    pitch_type: 'long',
    analyst_member_id: 'm19',
    approving_pm_member_id: 'm9',
    stage: 'research_in_progress',
    status: 'active',
    thesis_short: 'Copper deficit thesis intact; Grasberg execution de-risked',
    thesis_full: 'Electrification demand structural; supply constraints persist.',
    why_now: 'Copper inventories low; China stimulus rumors.',
    catalysts: ['Copper price rally', 'Grasberg output'],
    risks: ['Indonesia regulatory risk', 'Global recession'],
    target_price: 55,
    current_price_at_submission: 42,
    expected_return_pct: 31,
    time_horizon: '12m',
    research_due_at: '2026-04-22T23:59:00Z',
    created_at: daysAgo(11),
    updated_at: daysAgo(8),
  },
  {
    id: 'pitch-msft-1',
    team_id: 't1',
    ticker: 'MSFT',
    company_name: 'Microsoft',
    pitch_type: 'long',
    analyst_member_id: 'm13',
    approving_pm_member_id: 'm4',
    stage: 'pm_review',
    status: 'active',
    thesis_short: 'Azure AI attach driving ARPU expansion faster than modeled',
    thesis_full: 'Copilot monetization path clearer; enterprise penetration accelerating.',
    why_now: 'FY guidance likely conservative on AI revenue contribution.',
    catalysts: ['Copilot seats', 'Azure growth re-acceleration'],
    risks: ['Antitrust', 'OpenAI dependency'],
    target_price: 520,
    current_price_at_submission: 425.2,
    expected_return_pct: 22,
    time_horizon: '24m',
    created_at: daysAgo(21),
    updated_at: daysAgo(2),
  },
  {
    id: 'pitch-unh-1',
    team_id: 't1',
    ticker: 'UNH',
    company_name: 'UnitedHealth',
    pitch_type: 'long',
    analyst_member_id: 'm14',
    approving_pm_member_id: 'm4',
    stage: 'pm_review',
    status: 'active',
    thesis_short: 'Optum margin recovery post cyber incident over-discounted',
    thesis_full: 'Diversified healthcare platform; regulatory fears peaked.',
    why_now: 'Valuation at multi-year low vs historical premium.',
    catalysts: ['Optum growth', 'Medicare Advantage normalization'],
    risks: ['DOJ investigation', 'Medical cost trend'],
    target_price: 620,
    current_price_at_submission: 485,
    expected_return_pct: 28,
    time_horizon: '12m',
    created_at: daysAgo(18),
    updated_at: daysAgo(1),
  },
  {
    id: 'pitch-goog-1',
    team_id: 't7',
    ticker: 'GOOG',
    company_name: 'Alphabet',
    pitch_type: 'long',
    analyst_member_id: 'm11',
    approving_pm_member_id: 'm3',
    stage: 'committee_scheduled',
    status: 'active',
    thesis_short: 'Search AI integration protects ad share; Cloud profitable',
    thesis_full: 'Gemini distribution advantage; cost discipline improving margins.',
    why_now: 'Antitrust overhang partially priced; Cloud inflecting.',
    catalysts: ['AI Overviews monetization', 'Cloud margin expansion'],
    risks: ['Search disruption', 'Regulatory breakup'],
    target_price: 210,
    current_price_at_submission: 172.85,
    expected_return_pct: 21,
    time_horizon: 'long-term',
    committee_meeting_at: '2026-04-15T14:00:00Z',
    created_at: daysAgo(28),
    updated_at: daysAgo(4),
  },
  {
    id: 'pitch-tsla-1',
    team_id: 't4',
    ticker: 'TSLA',
    company_name: 'Tesla',
    pitch_type: 'short',
    analyst_member_id: 'm16',
    approving_pm_member_id: 'm6',
    stage: 'committee_vote',
    status: 'active',
    thesis_short: 'Margin compression + Robotaxi narrative over-owned',
    thesis_full: 'EV price war eroding auto gross margin; FSD timeline uncertain.',
    why_now: 'Q1 deliveries miss; competition intensifying in China.',
    catalysts: ['Delivery misses', 'Margin guide-down'],
    risks: ['Short squeeze', 'Musk distraction'],
    target_price: 140,
    current_price_at_submission: 178,
    expected_return_pct: 21,
    time_horizon: '3m',
    vote_yes_count: 3,
    vote_no_count: 2,
    vote_abstain_count: 0,
    committee_meeting_at: '2026-04-10T14:00:00Z',
    created_at: daysAgo(35),
    updated_at: daysAgo(1),
  },
  {
    id: 'pitch-jnj-arch-1',
    team_id: 't1',
    ticker: 'JNJ',
    company_name: 'Johnson & Johnson',
    pitch_type: 'long',
    analyst_member_id: 'm13',
    approving_pm_member_id: 'm4',
    stage: 'decision',
    status: 'accepted',
    thesis_short: 'Pharma spin clarity unlocks sum-of-parts re-rating',
    thesis_full: 'MedTech + Pharma pure-play valuations not reflected in conglomerate discount.',
    why_now: 'Talc litigation settlement path clearer.',
    catalysts: ['Kenvue separation complete', 'Pipeline approvals'],
    risks: ['Litigation tail', 'Patent cliffs'],
    target_price: 175,
    current_price_at_submission: 155,
    expected_return_pct: 13,
    time_horizon: '12m',
    decision: 'accepted',
    decision_at: daysAgo(12),
    decision_rationale: 'Strong risk/reward with litigation overhang largely priced.',
    vote_yes_count: 5,
    vote_no_count: 1,
    vote_abstain_count: 0,
    position_size_pct: 3.5,
    monitor_member_id: 'm14',
    archived_at: daysAgo(12),
    created_at: daysAgo(60),
    updated_at: daysAgo(12),
  },
  {
    id: 'pitch-meta-arch-1',
    team_id: 't7',
    ticker: 'META',
    company_name: 'Meta Platforms',
    pitch_type: 'long',
    analyst_member_id: 'm20',
    approving_pm_member_id: 'm3',
    stage: 'decision',
    status: 'rejected',
    thesis_short: 'Reels monetization + AI capex fears overdone',
    thesis_full: 'Ad efficiency improving; Reality Labs losses manageable at scale.',
    why_now: 'Efficiency year narrative intact; valuation reasonable vs peers.',
    catalysts: ['Reels ARPU', 'WhatsApp monetization'],
    risks: ['Reality Labs burn', 'Regulatory'],
    target_price: 580,
    current_price_at_submission: 510.6,
    expected_return_pct: 14,
    time_horizon: '12m',
    decision: 'rejected',
    decision_at: daysAgo(38),
    decision_rationale: 'Insufficient differentiation from existing mega-cap tech exposure.',
    vote_yes_count: 2,
    vote_no_count: 4,
    vote_abstain_count: 0,
    archived_at: daysAgo(38),
    created_at: daysAgo(55),
    updated_at: daysAgo(38),
  },
  {
    id: 'pitch-nvda-arch-1',
    team_id: 't7',
    ticker: 'NVDA',
    company_name: 'NVIDIA',
    pitch_type: 'long',
    analyst_member_id: 'm10',
    approving_pm_member_id: 'm3',
    stage: 'decision',
    status: 'accepted',
    thesis_short: 'AI infrastructure demand is structural, not cyclical',
    thesis_full: 'Data center GPU TAM expanding; CUDA ecosystem durable.',
    why_now: 'Hyperscaler capex guidance raised across board.',
    catalysts: ['H100/H200 demand', 'Software attach'],
    risks: ['Custom silicon', 'Export controls'],
    target_price: 750,
    current_price_at_submission: 520,
    expected_return_pct: 44,
    time_horizon: '12m',
    decision: 'accepted',
    decision_at: '2025-03-15T18:00:00Z',
    decision_rationale: 'Unanimous conviction on structural AI capex cycle.',
    vote_yes_count: 5,
    vote_no_count: 1,
    vote_abstain_count: 0,
    position_size_pct: 5,
    monitor_member_id: 'm10',
    archived_at: '2025-03-15T18:00:00Z',
    created_at: '2025-02-01T12:00:00Z',
    updated_at: '2025-03-15T18:00:00Z',
  },
  {
    id: 'pitch-amd-arch-1',
    team_id: 't7',
    ticker: 'AMD',
    company_name: 'Advanced Micro Devices',
    pitch_type: 'long',
    analyst_member_id: 'm11',
    approving_pm_member_id: 'm3',
    stage: 'decision',
    status: 'rejected',
    thesis_short: 'AI accelerator share gain vs NVDA incumbent advantage',
    thesis_full: 'MI300 competitive but CUDA moat limits share capture speed.',
    why_now: 'Hyperscaler diversification narrative gaining traction.',
    catalysts: ['MI300 volume', 'Server CPU share'],
    risks: ['NVDA dominance', 'Software ecosystem'],
    target_price: 180,
    current_price_at_submission: 145,
    expected_return_pct: 24,
    time_horizon: '6m',
    decision: 'rejected',
    decision_at: '2025-02-28T18:00:00Z',
    decision_rationale: 'Insufficient differentiation from MI300 incumbent advantage concerns.',
    vote_yes_count: 2,
    vote_no_count: 4,
    vote_abstain_count: 0,
    archived_at: '2025-02-28T18:00:00Z',
    created_at: '2025-02-10T12:00:00Z',
    updated_at: '2025-02-28T18:00:00Z',
  },
  {
    id: 'pitch-crm-arch-1',
    team_id: 't7',
    ticker: 'CRM',
    company_name: 'Salesforce',
    pitch_type: 'long',
    analyst_member_id: 'm24',
    approving_pm_member_id: 'm3',
    stage: 'decision',
    status: 'watchlist',
    thesis_short: 'Agentforce monetization could re-accelerate growth',
    thesis_full: 'Margin expansion story intact; AI agents early but promising.',
    why_now: 'Valuation compressed vs historical; wait for Agentforce KPIs.',
    catalysts: ['Agentforce ARR', 'Margin expansion'],
    risks: ['Competition', 'Integration complexity'],
    target_price: 320,
    current_price_at_submission: 295,
    expected_return_pct: 8,
    time_horizon: '6m',
    decision: 'watchlist',
    decision_at: daysAgo(45),
    decision_rationale: 'Interesting thesis but need more Agentforce traction evidence.',
    vote_yes_count: 3,
    vote_no_count: 2,
    vote_abstain_count: 1,
    archived_at: daysAgo(45),
    created_at: daysAgo(70),
    updated_at: daysAgo(45),
  },
];

export const MOCK_PITCH_DELIVERABLES = [
  {
    id: 'del-1',
    pitch_id: 'pitch-nvda-1',
    kind: 'model',
    title: 'NVDA DCF Model.xlsx',
    file_type: 'xlsx',
    file_size: 890000,
    uploaded_by_member_id: 'm10',
    uploaded_at: daysAgo(5),
  },
  {
    id: 'del-2',
    pitch_id: 'pitch-nvda-1',
    kind: 'memo',
    title: 'NVDA Investment Memo.pdf',
    file_type: 'pdf',
    file_size: 2100000,
    uploaded_by_member_id: 'm10',
    uploaded_at: daysAgo(4),
  },
  {
    id: 'del-3',
    pitch_id: 'pitch-nvda-1',
    kind: 'deck',
    title: 'NVDA Pitch Deck.pptx',
    file_type: 'pptx',
    file_size: 4200000,
    uploaded_by_member_id: 'm10',
    uploaded_at: daysAgo(3),
  },
  {
    id: 'del-4',
    pitch_id: 'pitch-msft-1',
    kind: 'model',
    title: 'MSFT Model.xlsx',
    file_type: 'xlsx',
    file_size: 1200000,
    uploaded_by_member_id: 'm13',
    uploaded_at: daysAgo(8),
  },
  {
    id: 'del-5',
    pitch_id: 'pitch-msft-1',
    kind: 'deck',
    title: 'MSFT Committee Deck.pptx',
    file_type: 'pptx',
    file_size: 5600000,
    uploaded_by_member_id: 'm13',
    uploaded_at: daysAgo(6),
  },
  {
    id: 'del-6',
    pitch_id: 'pitch-goog-1',
    kind: 'deck',
    title: 'GOOG Pitch Deck.pptx',
    file_type: 'pptx',
    file_size: 4800000,
    uploaded_by_member_id: 'm11',
    uploaded_at: daysAgo(10),
  },
  {
    id: 'del-7',
    pitch_id: 'pitch-goog-1',
    kind: 'memo',
    title: 'GOOG Memo.pdf',
    file_type: 'pdf',
    file_size: 1800000,
    uploaded_by_member_id: 'm11',
    uploaded_at: daysAgo(9),
  },
  {
    id: 'del-8',
    pitch_id: 'pitch-goog-1',
    kind: 'model',
    title: 'GOOG DCF.xlsx',
    file_type: 'xlsx',
    file_size: 950000,
    uploaded_by_member_id: 'm11',
    uploaded_at: daysAgo(8),
  },
  {
    id: 'del-9',
    pitch_id: 'pitch-goog-1',
    kind: 'one_pager',
    title: 'GOOG One-Pager.pdf',
    file_type: 'pdf',
    file_size: 420000,
    uploaded_by_member_id: 'm11',
    uploaded_at: daysAgo(7),
  },
];

export const MOCK_PITCH_VOTES = [
  {
    id: 'v1',
    pitch_id: 'pitch-tsla-1',
    voter_member_id: 'm1',
    vote: 'yes',
    rationale: 'Margin pressure visible in channel checks.',
    conviction_level: 4,
    recused: false,
  },
  {
    id: 'v2',
    pitch_id: 'pitch-tsla-1',
    voter_member_id: 'm2',
    vote: 'yes',
    rationale: 'EV competition thesis compelling.',
    conviction_level: 3,
    recused: false,
  },
  {
    id: 'v3',
    pitch_id: 'pitch-tsla-1',
    voter_member_id: 'm3',
    vote: 'no',
    rationale: 'Short squeeze risk too high near-term.',
    conviction_level: 2,
    recused: false,
  },
  {
    id: 'v4',
    pitch_id: 'pitch-tsla-1',
    voter_member_id: 'm25',
    vote: 'yes',
    rationale: 'Delivery data supports bear case.',
    conviction_level: 4,
    recused: false,
  },
  {
    id: 'v5',
    pitch_id: 'pitch-tsla-1',
    voter_member_id: 'm6',
    vote: 'no',
    rationale: 'Already underweight EV; prefer other shorts.',
    conviction_level: 2,
    recused: false,
  },
];

export const MOCK_PITCH_DISCUSSION = [
  {
    id: 'dm1',
    pitch_id: 'pitch-tsla-1',
    author_member_id: 'm1',
    parent_message_id: null,
    body: 'What is your base case for auto gross margin in Q2?',
    created_at: daysAgo(2),
  },
  {
    id: 'dm2',
    pitch_id: 'pitch-tsla-1',
    author_member_id: 'm16',
    parent_message_id: 'dm1',
    body: 'We model 16.5% vs Street 18.2% on China price cuts.',
    created_at: daysAgo(1),
  },
  {
    id: 'dm3',
    pitch_id: 'pitch-goog-1',
    author_member_id: 'm2',
    parent_message_id: null,
    body: 'How do you size AI Overviews monetization?',
    created_at: daysAgo(5),
  },
];

export const MOCK_PITCH_STAGE_HISTORY = [
  {
    id: 'h1',
    pitch_id: 'pitch-nvda-1',
    from_stage: null,
    to_stage: 'idea',
    actor_member_id: 'm10',
    note: 'Initial submission',
    created_at: daysAgo(14),
  },
  {
    id: 'h2',
    pitch_id: 'pitch-nvda-1',
    from_stage: 'idea',
    to_stage: 'research_approved',
    actor_member_id: 'm3',
    note: 'Approved for research — due Apr 12',
    created_at: daysAgo(12),
  },
  {
    id: 'h3',
    pitch_id: 'pitch-nvda-1',
    from_stage: 'research_approved',
    to_stage: 'research_in_progress',
    actor_member_id: 'm10',
    note: 'First deliverable uploaded',
    created_at: daysAgo(10),
  },
];

export const MOCK_PITCH_HINDSIGHT = {
  'pitch-nvda-arch-1': {
    pitch_id: 'pitch-nvda-arch-1',
    computed_at: daysAgo(1),
    current_price: 875.3,
    price_at_decision: 520,
    return_pct: 68.3,
    benchmark_return_pct: 12.1,
    alpha_pct: 56.2,
    max_drawdown_pct: -8.5,
    current_state: 'outperforming',
  },
  'pitch-amd-arch-1': {
    pitch_id: 'pitch-amd-arch-1',
    computed_at: daysAgo(1),
    current_price: 162.4,
    price_at_decision: 145,
    return_pct: 12.0,
    benchmark_return_pct: 9.2,
    alpha_pct: 2.8,
    max_drawdown_pct: -5.2,
    current_state: 'outperforming',
  },
  'pitch-meta-arch-1': {
    pitch_id: 'pitch-meta-arch-1',
    computed_at: daysAgo(1),
    current_price: 510.6,
    price_at_decision: 510.6,
    return_pct: 0,
    benchmark_return_pct: 8.5,
    alpha_pct: -8.5,
    max_drawdown_pct: -12.0,
    current_state: 'underperforming',
  },
  'pitch-jnj-arch-1': {
    pitch_id: 'pitch-jnj-arch-1',
    computed_at: daysAgo(1),
    current_price: 162,
    price_at_decision: 155,
    return_pct: 4.5,
    benchmark_return_pct: 6.2,
    alpha_pct: -1.7,
    max_drawdown_pct: -3.1,
    current_state: 'roughly_inline',
  },
};
