/**
 * Subscription plan metadata + Stripe Price IDs (public env vars).
 * Safe to import from client components — no secret keys.
 */

export const PLANS = {
  individual_monthly: {
    key: 'individual_monthly',
    name: 'Individual',
    price: 5,
    interval: 'month',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INDIVIDUAL_MONTHLY || null,
    features: [
      'Congressional trade alerts (24hr delay)',
      'Basic 13F filing access',
      'Community forum access',
      'Weekly market digest',
      'Watchlist (up to 10 tickers)',
      'Ezana Echo access',
      'Email notifications',
    ],
  },
  individual_yearly: {
    key: 'individual_yearly',
    name: 'Individual (Annual)',
    price: 48,
    interval: 'year',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_INDIVIDUAL_YEARLY || null,
    features: ['Everything in Individual monthly', 'Save 20% vs monthly'],
  },
  advanced_monthly: {
    key: 'advanced_monthly',
    name: 'Personal Advanced',
    price: 19,
    interval: 'month',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADVANCED_MONTHLY || null,
    features: [
      'Everything in Individual',
      'Real-time congressional alerts',
      'Full 13F filing database',
      'Legendary investor portfolios',
      'Advanced filtering & search',
      'Unlimited watchlists',
      'AI-powered company research',
      'API access (10K calls/mo)',
      'Priority support',
    ],
  },
  advanced_yearly: {
    key: 'advanced_yearly',
    name: 'Personal Advanced (Annual)',
    price: 180,
    interval: 'year',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ADVANCED_YEARLY || null,
    features: ['Everything in Personal Advanced monthly', 'Save 20% vs monthly'],
  },
  family_monthly: {
    key: 'family_monthly',
    name: 'Family',
    price: 49,
    interval: 'month',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_FAMILY_MONTHLY || null,
    features: [
      'Everything in Personal Advanced',
      'Up to 5 user accounts',
      'Shared watchlists & alerts',
      'Family portfolio dashboard',
      'Consolidated reporting',
      'Joint investment tracking',
      'API access on main account (25K calls/mo)',
      'Dedicated family support',
    ],
  },
  family_yearly: {
    key: 'family_yearly',
    name: 'Family (Annual)',
    price: 468,
    interval: 'year',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_FAMILY_YEARLY || null,
    features: ['Everything in Family monthly', 'Save 20% vs monthly'],
  },
  professional_monthly: {
    key: 'professional_monthly',
    name: 'Professional',
    price: 119,
    interval: 'month',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL_MONTHLY || null,
    features: [
      'Everything in Family',
      'Unlimited user accounts',
      'API access (100K calls/mo)',
      'Custom data exports & white-label reports',
      'Compliance & audit logs',
      'Team management & role-based access',
      'Copy trading infrastructure',
      'Dedicated account manager',
      'SLA guarantees',
      'Institutional-grade data feeds',
      'Direct support channel',
    ],
  },
  professional_yearly: {
    key: 'professional_yearly',
    name: 'Professional (Annual)',
    price: 1140,
    interval: 'year',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFESSIONAL_YEARLY || null,
    features: ['Everything in Professional monthly', 'Save 20% vs monthly'],
  },
};
