import { create } from 'zustand';

declare global {
  interface Window {
    __liveBillionaireScores?: Record<string, number>;
  }
}

export type PowerLayer =
  | 'trade'
  | 'conflict'
  | 'interest_rates'
  | 'economic'
  | 'military'
  | 'energy'
  | 'demographic'
  | 'governance'
  | 'infrastructure'
  | 'gdp'
  | 'debt'
  | 'population'
  | 'births'
  | 'wealth'
  | 'billionaires';

export interface CountryScore {
  iso: string;
  name: string;
  score: number;
}

interface GlobalPowerMapState {
  isOpen: boolean;
  selectedLayers: PowerLayer[];
  countryScores: CountryScore[];
  hoveredCountry: string | null;
  clickedCountry: string | null;
  toggleOpen: () => void;
  toggleLayer: (layer: PowerLayer) => void;
  clearLayers: () => void;
  setHoveredCountry: (iso: string | null) => void;
  setClickedCountry: (iso: string | null) => void;
  recomputeScores: () => void;
}

const layerScores: Record<PowerLayer, Record<string, number>> = {
  trade: {
    US: 94,
    CN: 92,
    DE: 78,
    JP: 74,
    KR: 68,
    NL: 65,
    GB: 62,
    FR: 60,
    IN: 52,
    BR: 45,
    MX: 42,
    RU: 38,
    CA: 72,
    AU: 55,
    IT: 57,
    SG: 80,
    SA: 48,
    AE: 58,
    CH: 70,
    SE: 62,
    NO: 60,
    TR: 44,
    ID: 46,
    TH: 50,
  },
  conflict: {
    US: 72,
    CN: 68,
    DE: 85,
    JP: 88,
    KR: 62,
    IN: 55,
    RU: 30,
    BR: 42,
    NG: 22,
    SD: 15,
    SY: 5,
    IQ: 18,
    AF: 8,
    ET: 25,
    MM: 20,
    ML: 18,
    GB: 80,
    FR: 78,
    AU: 84,
    CA: 82,
    SE: 88,
    NO: 90,
    FI: 92,
    CH: 90,
  },
  interest_rates: {
    US: 60,
    CN: 70,
    DE: 55,
    JP: 30,
    KR: 65,
    BR: 40,
    TR: 20,
    AR: 10,
    GB: 58,
    AU: 62,
    CA: 60,
    MX: 45,
    IN: 50,
    RU: 35,
    ZA: 38,
    NG: 25,
    CH: 72,
    SE: 58,
    NO: 64,
    DK: 60,
    NZ: 62,
    SG: 68,
  },
  economic: {
    US: 96,
    CN: 88,
    DE: 80,
    JP: 78,
    GB: 74,
    FR: 72,
    IN: 62,
    KR: 70,
    AU: 68,
    CA: 72,
    BR: 48,
    RU: 42,
    MX: 45,
    IT: 60,
    ES: 58,
    NL: 74,
    CH: 76,
    SE: 70,
    NO: 72,
    SG: 80,
    SA: 58,
    AE: 65,
    TR: 44,
    ID: 50,
  },
  military: {
    US: 99,
    CN: 85,
    RU: 80,
    IN: 68,
    GB: 65,
    FR: 64,
    JP: 58,
    DE: 55,
    KR: 62,
    IL: 70,
    SA: 52,
    TR: 55,
    PK: 45,
    BR: 42,
    AU: 50,
    CA: 48,
    IT: 50,
    ES: 48,
    NO: 46,
    SE: 52,
    PL: 55,
    UA: 58,
  },
  energy: {
    SA: 95,
    US: 88,
    RU: 90,
    CN: 72,
    NO: 80,
    CA: 78,
    AE: 85,
    QA: 90,
    AU: 70,
    BR: 60,
    NG: 55,
    IQ: 58,
    KZ: 60,
    MX: 50,
    GB: 48,
    DE: 40,
    IR: 65,
    KW: 80,
    LY: 58,
    VE: 45,
    IN: 42,
    ID: 50,
  },
  demographic: {
    IN: 88,
    CN: 75,
    US: 72,
    NG: 80,
    ID: 78,
    BR: 65,
    PK: 70,
    ET: 72,
    BD: 60,
    MX: 62,
    PH: 68,
    VN: 64,
    EG: 62,
    DE: 42,
    JP: 35,
    IT: 38,
    GB: 55,
    FR: 58,
    AU: 60,
    CA: 58,
    TR: 62,
    SA: 58,
  },
  governance: {
    FI: 98,
    DK: 97,
    NZ: 96,
    SE: 95,
    NO: 94,
    SG: 92,
    CH: 90,
    NL: 89,
    DE: 85,
    AU: 83,
    CA: 82,
    GB: 80,
    JP: 78,
    US: 72,
    FR: 70,
    KR: 68,
    IT: 58,
    ES: 60,
    PL: 62,
    CZ: 65,
    IL: 64,
    TW: 70,
  },
  infrastructure: {
    JP: 95,
    DE: 92,
    SG: 94,
    KR: 90,
    US: 88,
    CN: 84,
    FR: 82,
    GB: 80,
    AU: 78,
    CA: 76,
    NL: 80,
    CH: 88,
    AE: 82,
    SE: 84,
    FI: 82,
    AT: 80,
    DK: 82,
    NO: 78,
    IT: 70,
    ES: 68,
    PL: 60,
    IN: 50,
    BR: 48,
    TR: 52,
  },
  gdp: {
    US: 100,
    CN: 88,
    DE: 52,
    JP: 48,
    IN: 46,
    GB: 42,
    FR: 40,
    IT: 34,
    BR: 32,
    CA: 34,
    RU: 30,
    KR: 32,
    AU: 30,
    MX: 28,
    ES: 28,
    ID: 26,
    NL: 24,
    SA: 24,
    TR: 22,
    CH: 22,
    PL: 18,
    SE: 18,
    NO: 18,
    BE: 16,
    TH: 16,
    AT: 16,
    IL: 16,
    AE: 16,
    NG: 14,
    SG: 16,
    IE: 14,
    DK: 14,
    PH: 14,
    EG: 12,
    MY: 14,
    PK: 12,
    CL: 12,
    FI: 12,
    BD: 12,
    VN: 14,
    CZ: 12,
    CO: 12,
    ZA: 12,
    RO: 10,
    NZ: 10,
    PE: 10,
    QA: 10,
    HK: 14,
    KZ: 10,
    UA: 8,
    KW: 8,
    HU: 8,
    MA: 8,
    KE: 6,
    ET: 6,
  },
  debt: {
    JP: 8,
    GR: 12,
    IT: 18,
    US: 22,
    FR: 28,
    ES: 30,
    PT: 30,
    BE: 32,
    GB: 34,
    CA: 36,
    BR: 38,
    IN: 38,
    EG: 35,
    CN: 40,
    DE: 48,
    AT: 45,
    MX: 52,
    PL: 50,
    FI: 55,
    AU: 55,
    NL: 58,
    SE: 60,
    KR: 55,
    IL: 48,
    TR: 52,
    ZA: 42,
    NG: 62,
    TH: 58,
    ID: 65,
    CH: 72,
    NO: 68,
    DK: 62,
    NZ: 55,
    SG: 60,
    SA: 70,
    AE: 75,
    QA: 72,
    KW: 78,
    RU: 68,
    KZ: 70,
    TW: 60,
    MY: 58,
    PH: 55,
    VN: 52,
    PK: 40,
    BD: 50,
  },
  population: {
    IN: 100,
    CN: 98,
    US: 72,
    ID: 68,
    PK: 64,
    NG: 62,
    BR: 60,
    BD: 58,
    RU: 52,
    MX: 50,
    JP: 48,
    ET: 48,
    PH: 48,
    EG: 46,
    VN: 44,
    TR: 42,
    DE: 40,
    TH: 38,
    GB: 36,
    FR: 36,
    IT: 34,
    ZA: 34,
    TZ: 34,
    KE: 32,
    KR: 30,
    CO: 30,
    ES: 30,
    UA: 28,
    AR: 28,
    DZ: 28,
    SD: 28,
    IQ: 28,
    PL: 26,
    CA: 26,
    MA: 26,
    SA: 24,
    UZ: 24,
    MY: 24,
    AU: 22,
    NL: 20,
    CL: 18,
    KZ: 18,
    RO: 18,
    SY: 16,
    SE: 16,
    BE: 16,
    PT: 16,
    CZ: 16,
    HU: 16,
    GR: 16,
    AT: 16,
    CH: 16,
    IL: 16,
    SG: 12,
    NO: 12,
    DK: 12,
    FI: 12,
    NZ: 12,
    IE: 12,
    AE: 16,
    HK: 14,
    QA: 10,
    KW: 10,
  },
  births: {
    NG: 100,
    SD: 92,
    ET: 88,
    TZ: 86,
    KE: 82,
    UG: 80,
    ML: 84,
    AF: 90,
    IQ: 72,
    EG: 68,
    PK: 72,
    BD: 62,
    PH: 62,
    IN: 56,
    ID: 52,
    ZA: 58,
    MX: 48,
    BR: 44,
    CO: 42,
    VN: 42,
    SA: 50,
    MY: 46,
    TR: 44,
    AR: 40,
    US: 36,
    AU: 36,
    NZ: 38,
    FR: 38,
    GB: 36,
    SE: 38,
    NO: 36,
    DK: 34,
    NL: 34,
    CA: 32,
    DE: 28,
    CH: 30,
    AT: 30,
    BE: 32,
    FI: 28,
    CZ: 28,
    ES: 24,
    IT: 22,
    PL: 26,
    GR: 24,
    PT: 24,
    RU: 32,
    UA: 28,
    HU: 26,
    JP: 18,
    KR: 14,
    SG: 22,
    HK: 16,
    TW: 16,
    CN: 26,
  },
  wealth: {
    US: 100,
    CN: 78,
    JP: 58,
    GB: 56,
    DE: 54,
    FR: 50,
    IN: 48,
    CA: 46,
    AU: 48,
    IT: 42,
    KR: 40,
    ES: 36,
    CH: 44,
    NL: 38,
    TW: 36,
    BR: 34,
    SE: 34,
    HK: 36,
    SG: 32,
    SA: 30,
    MX: 28,
    ID: 28,
    TH: 26,
    AE: 28,
    NO: 30,
    BE: 28,
    AT: 26,
    DK: 26,
    IL: 28,
    IE: 26,
    PL: 22,
    ZA: 22,
    TR: 24,
    PH: 20,
    MY: 22,
    NG: 18,
    RU: 26,
    NZ: 24,
    AR: 18,
    CL: 20,
    FI: 24,
    CZ: 20,
    EG: 16,
    PK: 16,
    CO: 18,
    VN: 18,
    QA: 18,
    KW: 16,
    KE: 14,
    BD: 14,
    ET: 10,
    UA: 14,
  },
  billionaires: {
    US: 100,
    CN: 82,
    IN: 62,
    DE: 52,
    RU: 48,
    HK: 38,
    BR: 35,
    CA: 34,
    GB: 42,
    FR: 36,
    IT: 30,
    CH: 32,
    JP: 28,
    KR: 26,
    AU: 28,
    TW: 30,
    MX: 20,
    TH: 22,
    SE: 24,
    ES: 20,
    ID: 22,
    TR: 24,
    IL: 26,
    NO: 18,
    SG: 20,
    PH: 14,
    MY: 16,
    NG: 12,
    ZA: 14,
    NL: 18,
    CL: 10,
    CO: 10,
    PL: 12,
    AT: 14,
    DK: 12,
    SA: 16,
    AE: 18,
  },
};

const countryNames: Record<string, string> = {
  US: 'United States',
  CN: 'China',
  DE: 'Germany',
  JP: 'Japan',
  GB: 'United Kingdom',
  FR: 'France',
  IN: 'India',
  KR: 'South Korea',
  AU: 'Australia',
  CA: 'Canada',
  BR: 'Brazil',
  RU: 'Russia',
  MX: 'Mexico',
  IT: 'Italy',
  ES: 'Spain',
  NL: 'Netherlands',
  SA: 'Saudi Arabia',
  AE: 'UAE',
  NO: 'Norway',
  SE: 'Sweden',
  FI: 'Finland',
  DK: 'Denmark',
  CH: 'Switzerland',
  SG: 'Singapore',
  NG: 'Nigeria',
  ZA: 'South Africa',
  TR: 'Turkey',
  PK: 'Pakistan',
  ID: 'Indonesia',
  AR: 'Argentina',
  IL: 'Israel',
  EG: 'Egypt',
  SD: 'Sudan',
  SY: 'Syria',
  IQ: 'Iraq',
  AF: 'Afghanistan',
  ET: 'Ethiopia',
  MM: 'Myanmar',
  ML: 'Mali',
  BD: 'Bangladesh',
  PH: 'Philippines',
  VN: 'Vietnam',
  KZ: 'Kazakhstan',
  QA: 'Qatar',
  AT: 'Austria',
  NZ: 'New Zealand',
  PL: 'Poland',
  UA: 'Ukraine',
  CZ: 'Czech Republic',
  IR: 'Iran',
  KW: 'Kuwait',
  LY: 'Libya',
  VE: 'Venezuela',
  TW: 'Taiwan',
  TH: 'Thailand',
  MY: 'Malaysia',
  HK: 'Hong Kong',
  MA: 'Morocco',
  KE: 'Kenya',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Peru',
  BE: 'Belgium',
  IE: 'Ireland',
  PT: 'Portugal',
  GR: 'Greece',
  HU: 'Hungary',
  RO: 'Romania',
  UZ: 'Uzbekistan',
  UG: 'Uganda',
  TZ: 'Tanzania',
  DZ: 'Algeria',
};

function getLayerScoreSource(layer: PowerLayer): Record<string, number> {
  if (
    layer === 'billionaires' &&
    typeof window !== 'undefined' &&
    window.__liveBillionaireScores &&
    Object.keys(window.__liveBillionaireScores).length > 0
  ) {
    return window.__liveBillionaireScores;
  }
  return layerScores[layer];
}

function computeCompositeScores(layers: PowerLayer[]): CountryScore[] {
  if (layers.length === 0) return [];

  const allCountries = new Set<string>();
  layers.forEach((layer) => {
    Object.keys(getLayerScoreSource(layer)).forEach((iso) => allCountries.add(iso));
  });

  const scores: CountryScore[] = [];

  allCountries.forEach((iso) => {
    let total = 0;
    let count = 0;
    layers.forEach((layer) => {
      const source = getLayerScoreSource(layer);
      const v = source[iso];
      if (v !== undefined) {
        total += v;
        count += 1;
      }
    });
    if (count > 0) {
      scores.push({
        iso,
        name: countryNames[iso] || iso,
        score: Math.round(total / count),
      });
    }
  });

  return scores.sort((a, b) => b.score - a.score);
}

export const useGlobalPowerMap = create<GlobalPowerMapState>((set, get) => ({
  isOpen: false,
  selectedLayers: [],
  countryScores: [],
  hoveredCountry: null,
  clickedCountry: null,
  toggleOpen: () => set((s) => ({ isOpen: !s.isOpen })),
  toggleLayer: (layer) => {
    const current = get().selectedLayers;
    const next = current.includes(layer) ? current.filter((l) => l !== layer) : [...current, layer];
    set({ selectedLayers: next, countryScores: computeCompositeScores(next) });
  },
  clearLayers: () => {
    if (typeof window !== 'undefined') {
      delete window.__liveBillionaireScores;
    }
    set({ selectedLayers: [], countryScores: [], hoveredCountry: null, clickedCountry: null });
  },
  setHoveredCountry: (iso) => set({ hoveredCountry: iso }),
  setClickedCountry: (iso) => set({ clickedCountry: iso }),
  recomputeScores: () => {
    const layers = get().selectedLayers;
    set({ countryScores: computeCompositeScores(layers) });
  },
}));
