/**
 * Self-hosted web fonts. Run after changing a Fontsource package version:
 *   npm run fonts:build
 *
 * Copies the woff2 files the site uses from the Fontsource packages into
 * public/fonts/site/ and writes src/app/fonts.css with @font-face rules under
 * the family names the CSS already uses ("Plus Jakarta Sans", not Fontsource's
 * "Plus Jakarta Sans Variable"). Same ranges the site loaded from Google Fonts:
 *   Plus Jakarta Sans  variable 200 to 800, normal and italic
 *   JetBrains Mono     400, 500, 600, 700
 *   Newsreader         variable (covers 400 to 600), normal and italic
 *   Nunito             variable (covers 400 to 900)
 *   Cinzel             700
 * Every subset Fontsource ships keeps its unicode-range, so a browser only
 * downloads the scripts a page actually uses, as it did from Google.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public/fonts/site');
const OUT_CSS = join(ROOT, 'src/app/fonts.css');

const SOURCES = [
  ['@fontsource-variable/plus-jakarta-sans', ['wght.css', 'wght-italic.css'], 'Plus Jakarta Sans'],
  ['@fontsource/jetbrains-mono', ['400.css', '500.css', '600.css', '700.css'], 'JetBrains Mono'],
  ['@fontsource-variable/newsreader', ['wght.css', 'wght-italic.css'], 'Newsreader'],
  ['@fontsource-variable/nunito', ['wght.css'], 'Nunito'],
  ['@fontsource/cinzel', ['700.css'], 'Cinzel'],
];

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const blocks = [];
const files = new Set();
for (const [pkg, cssFiles, family] of SOURCES) {
  const dir = join(ROOT, 'node_modules', pkg);
  const version = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')).version;
  blocks.push(`/* ${family}: ${pkg}@${version} */`);
  for (const cssFile of cssFiles) {
    const css = readFileSync(join(dir, cssFile), 'utf8');
    for (const face of css.match(/@font-face\s*{[^}]*}/g) || []) {
      const woff2 = /url\(\.\/files\/([^)]+\.woff2)\)\s*format\('([^']+)'\)/.exec(face);
      if (!woff2) throw new Error(`${pkg}/${cssFile}: no woff2 source`);
      const [, file, format] = woff2;
      files.add(file);
      copyFileSync(join(dir, 'files', file), join(OUT_DIR, file));
      const keep = (prop) => (new RegExp(`${prop}:\\s*([^;]+);`).exec(face) || [])[1];
      blocks.push(
        [
          '@font-face {',
          `  font-family: '${family}';`,
          `  font-style: ${keep('font-style')};`,
          '  font-display: swap;',
          `  font-weight: ${keep('font-weight')};`,
          `  src: url('/fonts/site/${file}') format('${format}');`,
          `  unicode-range: ${keep('unicode-range')};`,
          '}',
        ].join('\n'),
      );
    }
  }
}

writeFileSync(
  OUT_CSS,
  `/* Generated by scripts/build-fonts.mjs (npm run fonts:build). Do not edit.
   Fonts are served from ezana.world, so loading a page sends nothing to a
   third-party font host. */\n\n${blocks.join('\n\n')}\n`,
);
console.log(`fonts: ${files.size} files into public/fonts/site, ${OUT_CSS}`);
