-- Seed platform changelog with v13 development-session updates (idempotent by title)

INSERT INTO public.platform_changelog_entries (title, body, category, is_pinned, is_published, released_at)
SELECT v.title, v.body, v.category, v.is_pinned, v.is_published, v.released_at::timestamptz
FROM (
  VALUES
    ('Live Portfolio Tracking on Weekly Chart', 'The "My Portfolio" line on the This Week on Ezana chart now uses live FMP quotes and historical closing prices to compute actual weekly returns from your mock trading positions. Previously showed 0% due to using cost basis instead of market value.', 'fix', false, true, '2026-05-10T22:57:00Z'),
    ('Compact Skill Rating Card', 'Removed the activity log from the Skill Rating card on the home page. The card now shows only your rating number, tier badge, and progress bar — clean and compact.', 'design', false, true, '2026-05-10T19:25:00Z'),
    ('This Week Chart: New Indices + Tooltips', 'Added VIX, WTI Crude, Brent Crude, and 10Y Treasury as comparison options on the This Week on Ezana chart. Each option now has an educational hover tooltip explaining what the index tracks and why it matters. Portfolio correlation badge (ρ) restored.', 'feature', true, true, '2026-05-10T19:07:00Z'),
    ('Sector-Grouped Stock Market Heatmap', 'The stock market heatmap on the Company Research page now groups tiles by sector (Technology, Finance, Healthcare, Consumer, Energy, Industrials) with sector name labels. Tile size is based on YTD return magnitude, not market cap — top performers get the biggest tiles.', 'feature', false, true, '2026-05-10T18:35:00Z'),
    ('Gold Premium Styling on Research Dropdown', 'Centaur Intelligence, Kairos Signal, Betting Markets, and For The Quants now have gold text and accent styling in the Research dropdown menu. Inside The Capitol moved to the bottom of the menu.', 'design', false, true, '2026-05-09T23:24:00Z'),
    ('Sector Colors on Dashboard Holdings', 'Each holding card on the dashboard now shows its sector color on the left accent bar and dot — matching the sector distribution pie chart. Time ranges expanded to 1D, 7D, 1M, 3M, 6M, 1Y, ALL on both Portfolio Snapshot and My Holdings.', 'improvement', false, true, '2026-05-09T22:50:00Z'),
    ('Day Streak, Skill Points, Community Fixes', 'Fixed the Day Streak counter (auto-creates tracking table on first login). Retroactive Elo points for users who completed learning center courses before the skill system launched. Community feed now filters by friends. Social Profiles replaced with Trending Topics. Suggested For You moved to KPI row.', 'fix', false, true, '2026-05-09T22:17:00Z'),
    ('Portfolio Snapshot Improvements', 'Expanded time range buttons to 1D, 7D, 1M, 3M, 6M, 1Y, ALL. Removed chart type toggle buttons. Replaced synthetic fake portfolio data with honest computed values or empty state.', 'improvement', false, true, '2026-05-09T21:19:00Z'),
    ('Fiber Optic Article Ticker Fix', 'Replaced European tickers (PRY, NEX) with US-listed companies mentioned in the article (AVGO, MSFT, AMZN). All 8 ticker buttons now open correctly on the Company Research page.', 'fix', false, true, '2026-05-09T20:01:00Z'),
    ('Echo Article Hero Images on Listing', 'Articles with hero images now display them as thumbnails on the Ezana Echo listing page. Category badges overlay on top-left of the image.', 'feature', false, true, '2026-05-08T21:21:00Z'),
    ('Semiconductor Charts Light Mode Fix', 'Fixed three semiconductor article charts that always rendered with dark backgrounds even in light mode. Root cause: charts used resolvedTheme (undefined) instead of theme from the ThemeProvider. Charts now spread throughout the article at contextually relevant positions.', 'fix', false, true, '2026-05-08T19:57:00Z'),
    ('Sector Dominance Article Cleanup', 'Removed redundant static hero image from the Tech Reigns article (it already has an interactive chart). Read time corrected from 18 to 4 minutes.', 'improvement', false, true, '2026-05-07T23:58:00Z'),
    ('Fiber Optic Article Hero Image', 'Added the Sopranos scene screenshot as the hero image for the Fiber Optic Cable article, visible both inside the article and on the Echo listing card.', 'content', false, true, '2026-05-07T23:47:00Z'),
    ('New Article: The Silicon Shield', 'Published "The Silicon Shield: How One Island Controls The World''s Chips" — a deep-dive into Taiwan''s semiconductor dominance, TSMC, the CHIPS Act, and the $5 trillion investment landscape. Features 3 interactive charts (market cap ranking, sortable financials table, foundry market share donut) and 10 educational keyword popups.', 'content', true, true, '2026-05-07T21:20:00Z'),
    ('Chart Click-to-Measure Feature', 'Added percentage change measurement tool to stock charts on Company Research and Mock Trading pages. Click a price point, move your mouse to see the % change between the two prices.', 'feature', false, true, '2026-05-07T20:35:00Z'),
    ('New Article: Hantavirus', 'Published "Hantavirus: From The Four Corners To The Open Sea" covering the 2026 MV Hondius cruise ship outbreak. Features 2 interactive charts (CDC yearly cases bar chart, state bubble map), 11 educational keywords, and investment analysis on biodefense, cruise lines, and diagnostics stocks.', 'content', false, true, '2026-05-06T22:49:00Z'),
    ('Targeted Notification System', 'Built a 4-layer notification intelligence system: user interest profiles from watchlist/portfolio/activity, event classification engine, relevance scoring with severity thresholds, and cron-based delivery to the bell icon. Includes 9 notification preference toggles in Settings.', 'feature', true, true, '2026-05-06T18:42:00Z'),
    ('Article Keywords: Fiber Optic + Iran', 'Added 18 green clickable keyword popups across both articles. 10 for fiber optic (PPI, CAGR, data center, MCF, hyperscale, supply chain, capex, single/multi-mode, margin of safety, dot-com bubble) and 8 for Iran commodities (Strait of Hormuz, commodity supercycle, sanctions, supply disruption, strategic reserves, backwardation, tungsten, fertilizer markets).', 'content', false, true, '2026-05-05T19:54:00Z'),
    ('DCF Dropdown Fix', 'Fixed all assumption variable dropdowns in the DCF Valuation card. The toolbar had overflow-x: auto which clipped the popover panels. Changed to flex-wrap with visible overflow. Popovers now drop down correctly into the chart area.', 'fix', false, true, '2026-05-05T18:08:00Z'),
    ('Market Opportunities Analysis Modal', 'Clicking a windfall or bane event now opens an in-page analysis modal instead of navigating to Centaur Intelligence. Modal shows AI-generated context, 5 related news articles, 3 KPI cards, confidence badge, and actionable insight — all tailored to the user''s risk profile.', 'feature', false, true, '2026-05-05T17:43:00Z'),
    ('Premium Gold Styling on All Models', 'All 9 stock analysis model cards on the Company Research page now use the gold premium design (gold border, gold text, gold star badge). Previously only DCF and Earnings had it.', 'design', false, true, '2026-05-05T15:56:00Z'),
    ('DCF Card Compact + Dark Mode Contrast', 'Removed the wide top band from the DCF card. Mode buttons (Forward/Reverse DCF) are 80% thinner with centered text. Bottom padding reduced. Added 14 dark mode contrast rules for readable text on dark backgrounds.', 'design', false, true, '2026-05-05T14:48:00Z'),
    ('Onboarding Continue Button Fix', 'Fixed the "Continue to Ezana" button on the questionnaire results screen. The button was wired to onCompleteRef which was never declared — clicking did nothing. Added the missing useRef declaration.', 'fix', false, true, '2026-05-04T18:41:00Z'),
    ('Centaur Intelligence Council Chamber', 'Redesigned the Centaur Intelligence page with a visual SVG "Council Chamber" — a horseshoe arrangement of 12 mythological-animal advisor chairs with a night skyline, rotating seal, and ambient speaking animations. Click any chair to see the advisor''s profile and start a meeting.', 'feature', true, true, '2026-05-04T17:55:00Z'),
    ('Clickable Top Movers + 52-Week Range', 'Top Movers rows on the home page are now clickable — clicking navigates to the Company Research page for that ticker. The volume display replaced with the 52-week price range ($LOW – $HIGH).', 'improvement', false, true, '2026-05-04T15:45:00Z'),
    ('Org Role-Based Onboarding + Market Opportunities', 'Organization members now get role-specific onboarding questionnaires: executives (9 questions with management style), portfolio managers (8 questions with strategy approach), analysts (7 questions). Org market opportunities API filters events by role — macro for execs, strategy for PMs, ticker-level for analysts.', 'feature', false, true, '2026-05-04T14:44:00Z'),
    ('Market Opportunities Card', 'New gold-bordered component card between Skill Rating and Congressional Tracker on the home page. Shows AI-curated windfalls and banes based on the user''s risk profile. Events sourced from FMP news and classified by sentiment.', 'feature', false, true, '2026-05-04T14:25:00Z'),
    ('Progressive Weekly Chart', 'The This Week on Ezana chart now shows only elapsed weekdays. On Monday, just one centered "Mon" point. Days are added progressively as the week unfolds. Larger dots for single-point days.', 'improvement', false, true, '2026-05-04T12:58:00Z'),
    ('Simplified Onboarding', 'Replaced the entire 714-line multi-step onboarding flow (phone, DOB, country, plan selection) with just the investor questionnaire. Users answer 7 questions about their experience, risk tolerance, and interests — then go straight to the dashboard.', 'improvement', false, true, '2026-05-04T11:30:00Z'),
    ('Investor Questionnaire', 'Built the onboarding investor profiling questionnaire — 7 questions covering experience level, asset class knowledge, risk tolerance, investment goals, financial literacy, savings allocation, and platform interests. Progress saved per-question. Computes an investor profile (Beginner/Intermediate/Advanced/Expert) with risk category for content personalization.', 'feature', true, true, '2026-05-04T00:01:00Z')
) AS v(title, body, category, is_pinned, is_published, released_at)
WHERE NOT EXISTS (
  SELECT 1 FROM public.platform_changelog_entries e WHERE e.title = v.title
);
